"""Updated models

Revision ID: 017616bd46ef
Revises: bce023ded585
Create Date: 2024-08-16 19:00:41.678501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017616bd46ef'
down_revision: Union[str, None] = 'bce023ded585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('economic_calendar_alerts_user_id_key', 'economic_calendar_alerts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('economic_calendar_alerts_user_id_key', 'economic_calendar_alerts', ['user_id'])
    # ### end Alembic commands ###
