"""Updated models

Revision ID: 590fb7ae35b5
Revises: 2b1b9fbde77e
Create Date: 2024-08-16 19:18:00.710035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590fb7ae35b5'
down_revision: Union[str, None] = '2b1b9fbde77e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
