"""Updated models

Revision ID: 6526076cf2a8
Revises: f89bde3429a2
Create Date: 2024-08-10 22:04:07.106836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6526076cf2a8'
down_revision: Union[str, None] = 'f89bde3429a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_calendar_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_name', sa.String(length=255), nullable=False),
    sa.Column('previous_value', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('event_exevution', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_table('economic_calendar_subs')
    op.drop_column('user', 'configuration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('configuration', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table('economic_calendar_subs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='economic_calendar_subs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='economic_calendar_subs_pkey'),
    sa.UniqueConstraint('user_id', name='economic_calendar_subs_user_id_key')
    )
    op.drop_table('economic_calendar_alerts')
    # ### end Alembic commands ###
