"""Updated models

Revision ID: f48a82e8dbee
Revises: 6526076cf2a8
Create Date: 2024-08-10 22:08:02.004919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48a82e8dbee'
down_revision: Union[str, None] = '6526076cf2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('economic_calendar_alerts', sa.Column('status', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('economic_calendar_alerts', 'status')
    # ### end Alembic commands ###
